#!/bin/bash
usage() { echo "Usage: $0 [-p <page number>] [-f <file name>]" 1>&2; exit 1; }

# Parsing inputs
while getopts ":p:f:" o; do
    case "${o}" in
        p)
            pages=${OPTARG}
            ;;
        f)
            file=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

# Defining the pages to be printed for each side
nstring=${#pages}  						# Number of characters in the string pages
dash_position=`expr index "$pages" -` 	# Finding the position where the dash is located
initial_page=${pages:0:dash_position-1}
ending_page=${pages:dash_position}

# Defining the page numbers for the front side
front_pages=
for (( c=$initial_page; c<=$ending_page; c=c+2 ))
do
		front_pages=${front_pages/%/$c,}  	# Stacking the page numbers
done
front_pages=${front_pages/%,/}				# Removing the last comma 

# Defining the page numbers for the back side
back_pages=
for (( c=$initial_page+1; c<=$ending_page; c=c+2 ))
do
		back_pages=${back_pages/%/$c,} 		# Stacking the page numbers
done
back_pages=${back_pages/%,/} 				# Removing the last comma

echo "Printing pages from the back side first"
lp -P $back_pages -o outputorder=reverse -o orientation-requested=6 "$file"

echo -n "Press 'c' to continue printing the pages from the front side"
read character
case $character in
    c ) lp -P $front_pages "$file" 
		echo "Finished"
        ;;
    * ) echo "Front side not printed"
esac
